### ISSUE TITLE
Add example for data in Rasa NLU format

### ISSUE THREAD

**Issue by BeWe11** [Revmaker/innatis#5]
There is no indication of how to input composite entities in the training data. The example data is given in the dialogflow format. It's rather hard to infer the format from the code. Can you provide an example?

Also, looking at the code, it seems that one has mark the complete text passage of a composite entity as a single entity in the "common examples" section of the training data, and the name of that entity has to match the name of a composite entity that is defined somewhere else. Is that correct?

Thank your for releasing this component!

**Comment by amitga-rnd** [comment]
:+1: 
First, your support for composite entities is very much appreciated!
I would also like to know how to use it... 
Currently all of my intents are in Rasa NLU format (markdown) not Json.

**Comment by eziolotta** [comment]
I would also like to use innatis, I really need composite entities in Rasa. Do i Can try with a dialogflow training file with composite entities ?? Will it work with unmodified rasa_nlu?

**Comment by akingbadeayobami** [comment]
@eziolotta Yes
@amitga-rnd There is really no way to use the composite entities with the markdown format without modifying the RASA core. I guess you have to convert your data to the JSON format to use the composite entities
